//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2007_Project1_Part3.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Game
    {
        public int gameID { get; set; }
        public string gameName { get; set; }
        public System.DateTime gameDate { get; set; }
        public string teamName { get; set; }
        public string description { get; set; }
        public int gameScore { get; set; }
    }
}
